Repository openturns/openturns, pull requests merged in 2022-10, with the labels that each got.

#2081 misc doc
  lib/src/Base/Graph/Graph.cxx
  lib/src/Base/Graph/GraphImplementation.cxx
  lib/src/Base/Graph/openturns/Graph.hxx
  lib/src/Base/Graph/openturns/GraphImplementation.hxx
  lib/src/Base/Optim/OptimizationResult.cxx
  lib/src/Uncertainty/Algorithm/Sensitivity/SobolIndicesAlgorithmImplementation.cxx
  python/doc/bibliography.rst
  python/doc/developer_guide/architecture.rst
  python/doc/examples/calibration/bayesian_calibration/plot_gibbs_simus.py
  python/doc/examples/data_analysis/sample_analysis/plot_src_confidence.py
  python/doc/examples/meta_modeling/polynomial_chaos_metamodel/plot_chaos_cantilever_beam_integration.py
  python/doc/examples/meta_modeling/polynomial_chaos_metamodel/plot_chaos_cleaning_strategy.py
  python/doc/examples/meta_modeling/polynomial_chaos_metamodel/plot_chaos_cv.py
  python/doc/examples/meta_modeling/polynomial_chaos_metamodel/plot_chaos_sobol_confidence.py
  python/doc/examples/meta_modeling/polynomial_chaos_metamodel/plot_enumeratefunction.py
  python/doc/examples/meta_modeling/polynomial_chaos_metamodel/plot_functional_chaos_advanced_ctors.py
  python/doc/theory/meta_modeling/enumeration_strategy.rst
  python/src/EnumerateFunctionImplementation_doc.i.in
  python/src/FunctionalChaosRandomVector_doc.i.in
  python/src/GraphImplementation_doc.i.in
  python/src/Graph_doc.i.in
  python/src/NormInfEnumerateFunction_doc.i.in
  python/src/StorageManager_doc.i.in
  python/src/Study_doc.i.in
  python/src/viewer.py
  python/test/t_PythonDistribution_save.py
  python/test/t_PythonPointToFieldFunction_load.py
  python/test/t_PythonPointToFieldFunction_save.py
  python/test/t_PythonRandomVector_save.py
Labels: doc

#2068 Improve truncated normal
  lib/src/Uncertainty/Distribution/DistFunc.cxx
  lib/src/Uncertainty/Distribution/TruncatedNormal.cxx
  lib/src/Uncertainty/Distribution/openturns/DistFunc.hxx
  lib/test/t_TruncatedNormal_std.cxx
  lib/test/t_TruncatedNormal_std.expout
  python/doc/user_manual/probabilistic_modelling.rst
  python/src/DistFunc_doc.i.in
  python/test/t_TruncatedNormal_std.expout
  python/test/t_TruncatedNormal_std.py
Labels: enhancement

#2150 Wingweight
  python/doc/examples/reliability_sensitivity/sensitivity_analysis/plot_sensitivity_wingweight.py
  python/doc/usecases/use_case_wingweight.rst
Labels: needs review
